const express = require("express");
const router = express.Router();
const passport = require("passport");
const session = require("express-session");
const bodyParser = require('body-parser');
const urlencodedParser = bodyParser.urlencoded({ extended: false });
const studentsController = require("../controllers/students_controller");
router.get("/getStudents", studentsController.getStudents);
router.get("/addstudent", studentsController.addStudent);
router.post("/create", studentsController.create);
router.post("/updateInterviewData", studentsController.updateInterviewData);
router.get("/downloadData", studentsController.downloadData);
module.exports = router;